Initialize a subscription service
prjctr-imazur/subscription-service pull request #1
Opened 2021-11-11 22:01 UTC by geekartisans

2021-11-12 11:09 UTC, welikoiwanenko requested changes

2021-11-12 11:09 UTC, welikoiwanenko commented on package.json
> +    "koa-body-parser": "0.2.1",
См. video-service

2021-11-12 16:03 UTC, geekartisans commented on package.json
> +    "koa-body-parser": "0.2.1",
исправил

2021-11-13 09:10 UTC, welikoiwanenko approved these changes

2021-11-18 18:34 UTC, merged